spring:
  application:
    name: furniture-task-tracker
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:/liquibase/changelog-master.yaml
  datasource:
    url: jdbc:postgresql://postgres:5432/furniture_count_db?currentSchema=furniture_task_tracker
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 10000
      maximum-pool-size: 5

springdoc:
  swagger-ui:
    path: /admin-swagger

loki:
  url: http://loki:3100

clock:
  timezone: Europe/Moscow