

spring:
  jpa:
    open-in-view: false
  datasource:
    url: jdbc:postgresql://postgres:5432/furniture_count_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 10000